### ISSUE TITLE
I have a problem on OS Ubuntu

### ISSUE THREAD

**Issue by kxvvv** [no-name-user-name/pyTelegramWalletApi#9]
My code works fine on Windows, but loading it on the server where OS Ubuntu is located, this error pops up: 
```Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1081, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1169, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1244, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 8404, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/root/telegram/telegram_p2p.py", line 403, in handle_start
    load_token()
  File "/root/telegram/get_wallet_token.py", line 4, in load_token
    c = Client(profile='main', headless=True)
  File "/usr/local/lib/python3.10/dist-packages/wallet/web_client.py", line 41, in __init__
    self.driver = webdriver.Chrome(chrome_options=options)
  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /root/.cache/selenium/chrome/linux64/125.0.6422.78/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55fcf91a167a <unknown>
#1 0x55fcf8ea265c <unknown>
#2 0x55fcf8ed6c95 <unknown>
#3 0x55fcf8ed2f8f <unknown>
#4 0x55fcf8f1c9a4 <unknown>
#5 0x55fcf8f10313 <unknown>
#6 0x55fcf8ee0586 <unknown>
#7 0x55fcf8ee0efe <unknown>
#8 0x55fcf916abbf <unknown>
#9 0x55fcf916ed4a <unknown>
#10 0x55fcf9158a1c <unknown>
#11 0x55fcf916f4d1 <unknown>
#12 0x55fcf913e82e <unknown>
#13 0x55fcf9190c68 <unknown>
#14 0x55fcf9190e76 <unknown>
#15 0x55fcf91a0731 <unknown>
#16 0x7f7915735ac3 <unknown>
```
I reinstalled the chrome driver and changed your code but still nothing works, need help:
```
options.binary_location = '/usr/bin/google-chrome'
self.driver = webdriver.Chrome(chrome_options=options)
```

```
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: no chrome binary at /usr/bin/google-chrome
Stacktrace:
#0 0x5562af61967a <unknown>
#1 0x5562af31a65c <unknown>
#2 0x5562af34ca47 <unknown>
#3 0x5562af34af8f <unknown>
#4 0x5562af3949a4 <unknown>
#5 0x5562af388313 <unknown>
#6 0x5562af358586 <unknown>
#7 0x5562af358efe <unknown>
#8 0x5562af5e2bbf <unknown>
#9 0x5562af5e6d4a <unknown>
#10 0x5562af5d0a1c <unknown>
#11 0x5562af5e74d1 <unknown>
#12 0x5562af5b682e <unknown>
#13 0x5562af608c68 <unknown>
#14 0x5562af608e76 <unknown>
#15 0x5562af618731 <unknown>
#16 0x7fb59c36aac3 <unknown>
```

**Comment by kxvvv** [comment]
it can only run on windows, right?

https://github.com/no-name-user-name/pyTelegramWalletApi/issues/2#issuecomment-1849458420

**Comment by no-name-user-name** [comment]
The library was developed and tested only on Windows

**Comment by kxvvv** [comment]
> The library was developed and tested only on Windows

ok, anyway, thanks a lot for the useful code <з
